### ISSUE TITLE
gRPC stops sending frames to inference and resets 

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#16] opened 2020-09-22 18:03 UTC
Issue: When we try to process images from rtpsim 1 camera at 30 fps the gRPC seem to reconnect making the solution choppy and break.

how to repo:: 
How to repro :
deploy vision on edge form here https://github.com/Azure-Samples/azure-intelligent-edge-patterns/tree/master/factory-ai-vision

try running the box-counting scenario

Expected::
the video should to continue seamlessly nd get frames at 30 fps on Xeon CPU  

Actual::
Video pause  then starts and pause as grpc stops and reconnects 

![image](https://user-images.githubusercontent.com/21267354/93920081-877a8f80-fcc3-11ea-9398-e1d2b0ce753b.png)

Help needed:: 
Can we get decoded images from LVA rather jpg to save on decoding time of 6-10ms
Can we send a sample for sending images for disply that uses encoding 

Give sampel with multi process for ai reference that 
     - video on one process and AI on another 

Logs:: 

INFO:root:Shared memory name: /dev/shm/inference_client_share_memory_13787989109186022346
INFO:root:Connection created with peer ipv4:172.18.0.5:36138.
MediaStreamDescriptor:
graph_identifier {
  graph_instance_name: "2"
  graph_node_name: "grpcExtension"
}
media_descriptor {
  timescale: 90000
  video_frame_sample_format {
    encoding: JPG
    dimensions {
      width: 960
      height: 540
    }
  }
}
shared_memory_buffer_transfer_properties {
  handle_name: "inference_client_share_memory_13787989109186022346"
  length_bytes: 52428800
}

**Comment by mustafakasap** [comment] 2020-09-25 18:03
**_- Can we get decoded images from LVA rather jpg to save on decoding time of 6-10ms_**
  Yes you can, this is explained in previous issue: https://github.com/Azure-Samples/live-video-analytics-iot-edge-python/issues/17 you can specify frame format (encoded in jpg png bmp etc.) or just raw byte array. Here dont forget the network load in case you start sending raw data with high fps and multi cameras.

 **_- Can we send a sample for sending images for disply that uses encoding_**
not clear. can you elaborate more? lea sends frames only to lvaExtension (which is you host your ai model or any business logic) you can tell LVA to send frames in any size, aspect ration, encoding (or raw) format to lvaExtension.

**_Give sampel with multi process for ai reference that - video on one process and AI on another_**
you can try using multiple processors. one for sending frames to lvaExtension1 (which is AI), another for lvaExtension2 (which is video.

**Comment by mustafakasap** [comment] 2020-09-25 18:09
_**Actual:: Video pause then starts and pause as grpc stops and reconnects**_

This issue (or not) related with third party RTSP simulator named Live555. This simulator is given as a sample for making basic tests and it is not for production. Live555 plays a video file like it is coming from a real IP camera (it is just a virtual IP camera for your tests). When the video ends, Live555 restarts, loop backs the video from the beginning but there is a several second gap occurs with also closing the existing RTSP Session. This issue is mentioned in Live555 forums with possible solution that needs some customization on this open source project.

This delay is not related to LVA and it is caused by Live555 external "sample" project. we recommend using longer video files for your simulations.

**Closed** 2020-09-25 19:16 UTC

**Comment by initmahesh** [comment] 2020-10-09 17:51
Again thanks for the feedback,
the issue reporting here is not the end of video delay on live 555 as we have made peace with that but here it just delays and randomly in between this repro on live rtsp as simulated rtsp
